import importlib.util
from pathlib import Path
import unittest

_MODULE_PATH = (
    Path(__file__).resolve().parents[1]
    / "anki_tts_addon"
    / "text_processing.py"
)
_SPEC = importlib.util.spec_from_file_location(
    "text_processing", _MODULE_PATH
)
_MODULE = importlib.util.module_from_spec(_SPEC)
assert _SPEC and _SPEC.loader
_SPEC.loader.exec_module(_MODULE)
extract_speakable_text = _MODULE.extract_speakable_text


EXAMPLE_RAW_CLOZE = (
    "<div>Antigen-<i>independent</i> <u>antibody diversity</u> in "
    "{{c1::<b>light</b>}} <b>chains</b> is generated by "
    "{{c2::<b>VJ</b>}}<b> gene recombination</b></div>"
)


class ExtractSpeakableTextTests(unittest.TestCase):
    def test_question_masks_only_active_second_cloze(self):
        result = extract_speakable_text(EXAMPLE_RAW_CLOZE, active_ord=1)

        self.assertEqual(
            result,
            (
                "Antigen-independent antibody diversity in light chains is "
                "generated by bla bla bla gene recombination"
            ),
        )

    def test_question_masks_only_active_first_cloze(self):
        result = extract_speakable_text(EXAMPLE_RAW_CLOZE, active_ord=0)

        self.assertEqual(
            result,
            (
                "Antigen-independent antibody diversity in bla bla bla chains "
                "is generated by VJ gene recombination"
            ),
        )

    def test_question_without_active_ord_masks_all_raw_clozes(self):
        result = extract_speakable_text(EXAMPLE_RAW_CLOZE, active_ord=None)

        self.assertEqual(
            result,
            (
                "Antigen-independent antibody diversity in bla bla bla chains "
                "is generated by bla bla bla gene recombination"
            ),
        )

    def test_answer_side_unwraps_raw_clozes_after_separator(self):
        html = (
            f"<div>front {EXAMPLE_RAW_CLOZE}</div>"
            '<hr id="answer">'
            f"<div>{EXAMPLE_RAW_CLOZE}</div>"
        )

        result = extract_speakable_text(
            html, strip_question=True, active_ord=1
        )

        self.assertEqual(
            result,
            (
                "Antigen-independent antibody diversity in light chains is "
                "generated by VJ gene recombination"
            ),
        )


if __name__ == "__main__":
    unittest.main()
